# Generated by Django 5.1.1 on 2024-11-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_payment_orderplaced_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Lagos', 'Lagos'), ('Ondo', 'Ondo'), ('Ekiti', 'Ekiti'), ('Osun', 'Osun'), ('Kwara', 'Kwara'), ('Cambridge', 'Cambridge'), ('London', 'London'), ('Manchester', 'Manchester'), ('Liverpool', 'Liverpool')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('ST', 'Select Tomatoes'), ('OT', 'Obaz Tomatoe Pack'), ('SP', 'Selected Pepper'), ('OP', 'Obaz Pepper Pack')], max_length=2),
        ),
    ]
