# Generated by Django 5.1.1 on 2024-11-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customer_state_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('ST', 'Select Tomatoes'), ('OT', 'Obaz Tomatoe Pack'), ('TP', 'Tomatoes Plum'), ('TK', 'Tomatoes Pack')], max_length=2),
        ),
    ]
